### ISSUE TITLE
Could not find file '/config/esphome/images/qr.png'

### ISSUE THREAD

**Issue by lboue** [kroon040/HA-Panel-GUITION#1]
A file seems to be missing in the images directory :
https://github.com/kroon040/HA-Panel-GUITION/blob/0a88d6d4f92e8cfc484fdd8f48a20efbcef18ef3/mypanel.yaml#L1909-L1911

And this leads to a building error:

```yaml
INFO ESPHome 2024.11.0-dev
INFO Reading configuration /config/esphome/panel-4.yaml...
INFO Detected timezone 'Europe/Paris'
Failed config

image: [source /config/esphome/panel-4.yaml:1897]
  - file: 
      path: images/back7.png
      source: local
    id: back7
    type: RGB565
    dither: NONE
    use_transparency: False
  - file: 
      path: images/back1.png
      source: local
    id: back1
    type: RGB565
    dither: NONE
    use_transparency: False
  - file: 
      path: images/ha_logo2.png
      source: local
    id: boot_logo
    type: RGB565
    dither: NONE
    use_transparency: False
  - 
    Could not find file '/config/esphome/images/qr.png'. Please make sure it exists (full path: /config/esphome/images/qr.png).
    file: images/qr.png
    id: qrimage
    type: RGB565
```

Where can I find it?

Best regards
